export const teamDetails = {
  "burak-celik": {
    name: "Burak Celik",
    slug: "burak-celik",
    title: "Principal",
    credentials: "Assoc. AIA",
    image: "/people/Burak.webp",
    location: "San Francisco, CA",
    tagline: "Designing at the intersection of narrative, technology, and craft.",
    bio: "Burak is a co-founding principal of YCD Studio, bringing a deep background in institutional, cultural, and competition-scale design to the firm's commercial and hospitality practice. Before YCD, he shaped projects at HDR Architecture, Oyler Wu Collaborative, Studio Libeskind, and Melike Altınışık — spanning museums, memorials, labs, and towers across three continents.",
    philosophy: "Architecture should feel inevitable — like it was always meant to be there. I start every project by listening for the story the site and the client are already telling, then I work to give that story a physical form that's precise enough to build and open enough to evolve.",
    experiences: [
      {
        company: "HDR Architecture Inc.",
        role: "Project Designer",
        period: "Sep 2021 – Apr 2024",
        location: "Los Angeles, CA",
        projects: [
          { name: "BIONICA", note: "Award-winning competition" },
          { name: "PBRB Lab Building & Pavilion", note: "SD & DD phases" },
          { name: "Design for Others Zambia", note: "Project Designer, Client Coordinator" },
          { name: "YWCA of the Harbor Area", note: "Proposal, Conceptual" },
          { name: "OC Public Health Lab", note: "Schematic phase" },
          { name: "Future Labs", note: null },
        ],
      },
      {
        company: "Oyler Wu Collaborative",
        role: "Designer",
        period: "May 2020 – Sep 2020",
        location: "Los Angeles, CA",
        projects: [
          { name: "Kaohsiung Museum of Fine Arts", note: "Under Construction" },
          { name: "2450 Hyperion Project", note: "Constructed" },
          { name: "2415 St George House", note: "Constructed" },
          { name: "Ivan Hill Housing", note: null },
          { name: "LACE", note: "Jewelry" },
        ],
      },
      {
        company: "Studio Libeskind",
        role: "Designer",
        period: "Jan 2019 – Jul 2019",
        location: "New York, NY",
        projects: [
          { name: "Through the Lens of Faith", note: "Constructed" },
          { name: "Names Memorial", note: "Under Construction" },
          { name: "Danish Jewish Museum", note: null },
          { name: "COOP Zurich", note: null },
          { name: "Iquique Museum", note: null },
        ],
      },
      {
        company: "Melike Altınışık Architects",
        role: "Designer",
        period: "Jul 2017 – Sep 2017",
        location: "Istanbul, Turkey",
        projects: [
          { name: "Çamlıca TV Tower", note: "Under Construction, Istanbul" },
          { name: "IABA 2017", note: "Constructed, Antalya" },
          { name: "AFA Cultural Center", note: "Sakarya" },
          { name: "Süleymanpaşa Municipality Competition", note: "Tekirdağ" },
          { name: "Ahlat Youth Center Competition", note: "Bitlis" },
        ],
      },
    ],
    stats: [
      { value: "4", label: "Firms across 3 continents" },
      { value: "20+", label: "Projects shaped" },
      { value: "7", label: "Years of practice" },
      { value: "3", label: "Countries worked in" },
    ],
  },
};
