export const teamDetails = {
  "burak-celik": {
    name: "Burak Celik",
    slug: "burak-celik",
    title: "Principal",
    credentials: "Assoc. AIA",
    image: "/people/Burak.webp",
    location: "San Francisco, CA",
    tagline: "Designing at the intersection of narrative, technology, and craft.",
    bio: "Burak is a co-founding principal of YCD Studio, bringing a deep background in institutional, cultural, and competition-scale design to the firm's commercial and hospitality practice. Before YCD, he shaped projects at HDR Architecture, Oyler Wu Collaborative, Studio Libeskind, and Melike Altınışık — spanning museums, memorials, labs, and towers across three continents.",
    philosophy: "Architecture should feel inevitable — like it was always meant to be there. I start every project by listening for the story the site and the client are already telling, then I work to give that story a physical form that's precise enough to build and open enough to evolve.",
    journey: [
      { city: "Istanbul", x: 57.5, y: 34 },
      { city: "New York", x: 25.5, y: 33 },
      { city: "Los Angeles", x: 15, y: 36 },
      { city: "San Francisco", x: 14, y: 33.5 },
    ],
    experiences: [
      {
        company: "HDR Architecture Inc.",
        role: "Project Designer",
        period: "Sep 2021 – Apr 2024",
        location: "Los Angeles, CA",
        projects: [
          { name: "BIONICA", note: "Award-winning competition" },
          { name: "PBRB Lab Building & Pavilion", note: "SD & DD phases" },
          { name: "Design for Others Zambia", note: "Project Designer, Client Coordinator" },
          { name: "YWCA of the Harbor Area", note: "Proposal, Conceptual" },
          { name: "OC Public Health Lab", note: "Schematic phase" },
          { name: "Future Labs", note: null },
        ],
      },
      {
        company: "Oyler Wu Collaborative",
        role: "Designer",
        period: "May 2020 – Sep 2020",
        location: "Los Angeles, CA",
        projects: [
          { name: "Kaohsiung Museum of Fine Arts", note: "Under Construction" },
          { name: "2450 Hyperion Project", note: "Constructed" },
          { name: "2415 St George House", note: "Constructed" },
          { name: "Ivan Hill Housing", note: null },
          { name: "LACE", note: "Jewelry" },
        ],
      },
      {
        company: "Studio Libeskind",
        role: "Designer",
        period: "Jan 2019 – Jul 2019",
        location: "New York, NY",
        projects: [
          { name: "Through the Lens of Faith", note: "Constructed" },
          { name: "Names Memorial", note: "Under Construction" },
          { name: "Danish Jewish Museum", note: null },
          { name: "COOP Zurich", note: null },
          { name: "Iquique Museum", note: null },
        ],
      },
      {
        company: "Melike Altınışık Architects",
        role: "Designer",
        period: "Jul 2017 – Sep 2017",
        location: "Istanbul, Turkey",
        projects: [
          { name: "Çamlıca TV Tower", note: "Under Construction, Istanbul" },
          { name: "IABA 2017", note: "Constructed, Antalya" },
          { name: "AFA Cultural Center", note: "Sakarya" },
          { name: "Süleymanpaşa Municipality Competition", note: "Tekirdağ" },
          { name: "Ahlat Youth Center Competition", note: "Bitlis" },
        ],
      },
    ],
    stats: [
      { value: 4, label: "Firms across 3 continents" },
      { value: 20, suffix: "+", label: "Projects shaped" },
      { value: 7, label: "Years of practice" },
      { value: 3, label: "Countries worked in" },
    ],
    publications: [
      {
        outlet: "Interior Design Magazine",
        title: "Architects Envision a Sustainable Martian Habitat",
        url: "https://interiordesign.net/designwire/architects-burak-celik-zeynep-ege-odabasi-and-naz-kaplan-envision-a-sustainable-martian-habitat/",
      },
      {
        outlet: "ArchDaily",
        title: "Oyler Wu & Ren Lai to Re-Envision Kaohsiung Museum of Fine Arts",
        url: "https://www.archdaily.com/951754/oyler-wu-collaborative-and-ren-lai-architects-to-re-envision-the-kaohsiung-museum-of-fine-arts-in-taiwan",
      },
      {
        outlet: "Architizer",
        title: "Genesis V2 — Mars Colony Prototype",
        url: "https://architizer.com/projects/genesis-v2/",
      },
      {
        outlet: "Archinect",
        title: "SCI-Arc Graduate & Gehry Prize Winner Proposes New Perspectives",
        url: "https://archinect.com/features/article/150284209/sci-arc-graduate-and-2021-gehry-prize-winner-proposes-new-perspectives-between-city-structures-and-augmented-reality-holograms",
      },
      {
        outlet: "designboom",
        title: "Genesis V2 — Adaptable Sustainable Housing Colony for Mars",
        url: "https://www.designboom.com/architecture/genesis-v2-adaptable-sustainable-prototype-housing-colony-mars-01-26-2022/",
      },
      {
        outlet: "Interesting Engineering",
        title: "Colony Design for Mars",
        url: "https://interestingengineering.com/innovation/colony-design-for-mars",
      },
      {
        outlet: "Yanko Design",
        title: "Martian Colony Concept — Sustainable Off-Planet Housing",
        url: "https://www.yankodesign.com/2022/02/05/this-martian-colony-concept-imagines-what-sustainable-off-planet-housing-could-look-like/",
      },
      {
        outlet: "Inhabitat",
        title: "Designers Imagine Sustainable Housing on Mars",
        url: "https://inhabitat.com/a-team-of-designers-imagines-sustainable-housing-on-mars/",
      },
      {
        outlet: "SCI-Arc",
        title: "Oyler Wu Collaborative — Featured Studio Work",
        url: "https://www.sciarc.edu/news/2021/oyler-wu",
      },
      {
        outlet: "Architect Magazine",
        title: "Meditations on the Harem",
        url: "https://www.architectmagazine.com/project-gallery/meditations-on-the-harem",
      },
      {
        outlet: "Studio Mercado",
        title: "Haremde Meditasyon",
        url: "https://www.studiomercado.com/post/haremde-meditasyon",
      },
      {
        outlet: "Arkiv",
        title: "Motion in the Shell — Kabuktaki Hareket",
        url: "http://www.arkiv.com.tr/proje/motion-in-the-shell---kabuktaki-hareket/8176",
      },
      {
        outlet: "Arkitera",
        title: "Superpositioning 2",
        url: "https://www.arkitera.com/en/project/superpositioning-2/",
      },
      {
        outlet: "VoyageLA",
        title: "Meet Burak Celik of Arts District",
        url: "https://voyagela.com/interview/meet-burak-celik-of-arts-district/",
      },
      {
        outlet: "World Architecture Community",
        title: "The Living Machine — A Prototype for a Sustainable Urban Environment",
        url: "https://worldarchitecture.org/architecture-projects/hpzvp/the-living-machine--a-prototype-for-a-sustainable-urban-environment-project-pages.html",
      },
    ],
  },
};
